on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/delivery.yml"
      - "jotobot/**"
      - ".dockerignore"
      - "Dockerfile"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: docker
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/cytheworker/jotobot:latest