on:
  push:
    branches:
      - main

jobs:
  ghcr:
    runs-on: ubuntu-latest
    environment: ghcr

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in registry

        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/cytheworker/jotobot:latest