on:
  - push
  - pull_request

jobs:
  source:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Set up dependencies
        run: poetry install --no-dev

      - name: Execute Pyright
        uses: jakebailey/pyright-action@v1

      - name: Execute Flake8
        uses: py-actions/flake8@v2

  image:
    needs: source
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: cytheworker/jotobot:latest